### ISSUE TITLE
Album Gain Support

### ISSUE THREAD

**Issue by skattman** [Sappharad/mp3gainOSX#13]
I think your interface is much more polished than the other options for OS X, unfortunately, I need the ability to use the album gain feature of MP3Gain.  Is this a feature you'd be willing to consider implementing?

**Comment by gith-account** [comment]
Hi, could this be implemented, please? The port is great otherwise, but album gain is definitely missing and it would be a pity to have to create another port only for this, especially since you have mentioned that it would be rather easy for you to add it.

**Comment by Sappharad** [comment]
I don't see why someone would need to "create another port" for that, this one is open source and they could just add it themselves and submit a pull request. I don't mind if someone else wants to do a better job. There was already another port available when I started this one, but it was abandoned and just an AppleScript wrapper around an old command-line build.

Regarding an update on this, I actually partially finished adding album gain last July. The GUI changes were done and Analyze was implemented, but not Apply Gain. However, I paused before finishing it because the way I had originally decided to integrate the port with MP3Gain's code made it difficult to get the progress status back to the UI. It also made some other requests like multi-threaded processing impossible. I decided to completely rewrite the backend to make multi-core processing possible, (which the Windows version doesn't even do) and made it as far as working proof of concept where I could analyze multiple files at a time but didn't have a new UI for that yet. I got busy and haven't touched it since August though. Also, multi-core and album gain are mutually exclusive, because album gain just treats multiple tracks as a single track so you can't process multiple files at once anyway, but I need to finish those changes before I can hook up Album gain to the new backend. I have no idea at this point when I'll finally resume working on the rewrite, but every time I get a reminder like this it helps.

At the moment, your best option is just to use the command-line build which is also available for download on the website. That has all functionality of MP3Gain including AACGain support, you just have to know how to use the terminal.

**Comment by gith-account** [comment]
> I don't see why someone would need to "create another port" for that, this one is open source and they could just add it themselves and submit a pull request.

You are absolutely right about that. Sorry, that was poor wording on my behalf.

I am not a programmer myself and a newcomer to MacOS. Adding this feature to your port is beyond my skills. My alternate strategy would be to take your command line build (thanks a lot for that, btw.), look into AppleScript and see what I can achieve. That is a frustrating thought for me, because I will probably be putting a lot of work into something that may or may not work, with zero chance to achieve something nice like your tool, which does the job great and is only missing this tiny bit. This is where the "to have to create" part came from. I mixed up several thoughts there.

> I don't mind if someone else wants to do a better job.

I would like it better if that (hypothetical) someone put his or her effort into contributing to your port. There are, of course, many good reasons for starting new projects around the same problem, but in this case collaborating with you on your port, which is close to being feature complete, would be the better thing to do, imho.

I would like to appologize if I came across as rude or made it look like I did not appreciate your work. I am super happy that you created a build of the command line tool and that your are still actively working on the graphical tool. Thanks a lot for all your work!

**Comment by Sappharad** [comment]
Here's a status update. I started working on this again recently. The backend changes necessary to support multi-core processing, album gain and AAC support are mostly done now. Since multiple files can be processed at once, the UI for that has changed to what's pictured below. 
<img width="570" alt="m3g_multicore" src="https://cloud.githubusercontent.com/assets/1350664/25511769/9645a9d2-2b8e-11e7-8a84-76dfef1a7fe5.png">
Everything still needs to be hooked back up, (only Analyze does something in my current development build) but the hardest part is done. A new release could still end up being a month or more away depending on how often I work on it, but I don't think it should be very long now.

Since I significantly changed how things work internally, I might release a beta for people to try out before doing the next release to make sure I didn't break anything. I'll post here if / when I have more news.

**Comment by Sappharad** [comment]
Added in 05ed8d73ab206d093d3b141d150d82ac0c737148.
This will be closed when 2.0 is released.

**Comment by Sappharad** [comment]
If you want to try it, MP3Gain Express 2.0 beta (which is version 1.9 in the About box so that Check for Updates will work correctly when 2.0 is actually released) can be downloaded here:
http://projects.sappharad.com/mp3gain/mp3gain_mac19beta.zip

I don’t think it should damage anything, and the Undo feature is still hiding under the little arrow menu, but it’s always a good idea to test with a copy of the files instead of originals until you’ve determined that the program works correctly.

Changes:
- Multi-Core Processing (currently hard-coded to 2 files at once, this will be configurable in the final release)
- New icons to match macOS Yosemite and newer. If using the dark mode for menus and dock, MP3Gain Express will also be dark.
- Album Gain
- Value set for Normal volume is actually checked now so users don’t enter a bad number

Known problems:
- Spanish localization was not updated yet and the app will be broken if your language is set to Spanish.
- Multi-Core processing is hard-coded to 2 files at once.
- When resizing the window in dark mode, the file list sometimes flickers. This isn’t a big deal and fixing it easily would require dropping support for versions of macOS older than Yosemite, so I’m leaving it alone.

If you decide to try it, please let me know if it appears to still work fine or if you run into problems. Version 2.0 will not be released until I've added a few more features, and confirmed that the program is still working correctly after all of the changes I made.

**Comment by StarlightDesign** [comment]
Thanks for following up, that newer beta version is back up and running. It's much appreciated!

**Comment by Sappharad** [comment]
MP3Gain Express 2.0 has been released.
