### ISSUE TITLE
Website is missing

### ISSUE THREAD

**Issue by staktrace** [Sappharad/mp3gainOSX#23]
http://projects.sappharad.com/mp3gain/ (URL listed in the project description) is producing a 404 error. The similar URL http://projects.sappharad.com/tools/mp3gain.html linked to from the mp3gain author's website at http://mp3gain.sourceforge.net/download.php is also returning a 404 error.

**Comment by Sappharad** [comment]
Works for me.

**Comment by staktrace** [comment]
Weird, works for me now as well. I swear it wasn't working when I tried it a little bit ago. I was getting an nginx 404 page. I also tried the https version and that gave me a cert error (which is still happening). But I'll close this as I can't repro any more. Sorry for the noise.

**Comment by Sappharad** [comment]
The SSL problem has been happening since I switched servers in June. I need to fix that one still. Thanks for reminding me.
It’s using the cert for one of my other sites and refusing to generate one for projects.sappharad.com even though the main site works fine.

**Comment by Sappharad** [comment]
SSL is now working again for
https://projects.sappharad.com/

It's also working correctly for www.sappharad.com as well, which had been behaving strangely since I set up the new server in June. Safari would randomly say the cert was bad, then on refresh decide the cert was perfectly fine, then on another refresh go back to not liking it. I managed to run into the 404 problem myself from Safari trying to get to the main site. 

I believe the cause of all of these problems came from my attempt to support IPv6 on the new server. I removed the IPv6 entries from DNS for both domains and SSL certificates generated correctly for both and they now work correctly. I think I might need to create a unique IPv6 address for each subdomain for everything to work correctly with my current setup. I'll do this some day if it ever becomes necessary, but in the meantime what works is fine.
