### ISSUE TITLE
Album mode analysis gets cached and stuck

### ISSUE THREAD

**Issue by electrovir** [Sappharad/mp3gainOSX#31]
When I analyze a bunch of files in `Album Mode`, the results apparently get cached (even between restarts of the app) for the files I analyzed because unchecking `Album Mode` does not result in a file-by-file reanalysis, it still shows the same results from the `Album Mode` analysis.

**Comment by electrovir** [comment]
This persists after account log out as well.

**Comment by Sappharad** [comment]
The opposite is true. Album mode means nothing if you are doing "Analyze" because the app is just determining the loudness of each file and saving that information as tags in the file so that MP3 Players with ReplayGain support can use the tags to handle volume themselves.

My thought at the time was that if we're just determining the loudness of the files why do I need to care about the album as a whole because once we know each file you can just use the loudest one to determine what you do with the others. At some point I had the same thought for Apply and I was doing two passes, one to analyze individual files and a second to apply, but I found that the command line app was not even using the individual file data to apply for album and just recalculated everything so I had to change that.

I can try to change this for analyze if you'd like, (if it's even possible, I haven't checked) but I don't see what the point of analyzing in album mode is. If you're not actually changing the files then having the loudness for individual files should be enough to know what the album as a whole needs to be.

**Comment by electrovir** [comment]
I must not be understanding something then. This is what happens for me:

1. I add a folder that hasn't been analyzed yet
2. I click `Analyze Only`
3. Each track is analyzed and shows its own stats
4. I check `Album Mode` and click `Analyze Only` again
5. All tracks have the same `Volume` and `Track Gain` (as makes sense, I think, for `Album Mode`)
6. I uncheck `Album Mode` and click `Analyze Only` again
7. The `Album Mode` numbers persist

> saving that information as tags in the file
This was the key thing that I was missing though. As long as I backup my mp3 files or figure out how to remove the tags (which I'm sure is easy but I'm new to this stuff) then I can just duplicate the backups and analyze them again to see the original track numbers.

Ultimately I need a lot more automation than the UI provides so I'm going to take a shot at the command line tool.

Thanks!

**Comment by Sappharad** [comment]
@electrovir Please let me know when you've found a solution to your problem.
It could just be that I'm failing to understand the value of Analyze in combination with Album, and if I'm doing it wrong in the UI I could fix that.

**Comment by electrovir** [comment]
I ended up finding [a tool that was already built for my very-specific use-case](https://github.com/Clysop/Normalizer-for-Clone-Hero). 
Thus, I didn't end up using CLI of this tool. I'm not sure if the `Album Mode` experience is accurate or not... sorry for the bother!

**Comment by Sappharad** [comment]
@electrovir That tells me that you probably did not want Album mode in the first place, and track mode was probably correct for your purpose.

Album mode treats the entire list of songs as one song - If the loudest song needs to be raised by 3dB then all songs are raised by 3dB. Track mode (the normal mode) checks all tracks individually. If the maximum volume of one track is lower than the others, it will only update the tracks that are too quiet, and vice versa.

Album mode is only useful when you have an actual album / CD performed concert style with no breaks between tracks such that the music continues from one track to the next - you wouldn't want the music to suddenly get louder or quieter as they transition between songs.

In your case, Clone Hero you are playing 1 song at a time, so you wanted to scan each track individually and raise the volume on it. Not Album mode.

That's good for me, I don't need to change anything. Thanks for clearing this up.
